### ISSUE TITLE
Finding relics without also enabling bravery/randomize modes

### ISSUE THREAD

**Issue by VZ326** [minavoii/sanctuary-seeder#1]
Hello, I was wondering if it was possible to add a function in the seed finder only for chaos relics. The program asks you to select randomaizer or bravery for that function, however, in the areas section it tells you which objects appear in the chests only with the relics activated and it works correctly. Thank you in advance.

**Comment by minavoii** [comment]
This would require further increasing the size of the local database, and provides little advantage as any relic is found in most seeds.
